# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "dev" do |dev|
        dev.vm.box = "ubuntu/bionic64"
        dev.vm.network "forwarded_port", guest: 80, host: 1234, host_ip: "127.0.0.1"
        dev.vm.network "forwarded_port", guest: 443, host: 1235, host_ip: "127.0.0.1"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/deploy.yml"
        ansible.groups = {
            "all" => ["dev"],
        }
    end
end
