---
# tasks file for php

- name: remove wrong version
  apt:
    name: php
    state: absent

- name: Install PHP repo
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP to correct version
  apt:
    #name: "php{{target_php_version}}"
    name: php7.4
    state: present

- name: Install necessary PHP modules
  apt:
    name: "php{{php_version}}-{{item}}"
    state: latest
  loop: "{{required_php_modules}}"

- name: ensure correct directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  loop:
    - "{{ php_config_directory }}"
    - "{{ php_config_directory }}/fpm"
    - "{{ php_config_directory }}/fpm/pool.d"
    - "{{ php_config_directory }}/cli"

- name: install php configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'fpm.php.ini.j2', dest: '{{ php_config_directory }}/fpm/php.ini' }
    - { src: 'www.conf.j2', dest: '{{ php_config_directory }}/fpm/pool.d/www.conf' }
    - { src: 'php-fpm.conf.j2', dest: '{{ php_config_directory }}/fpm/php-fpm.conf' }
    - { src: 'cli.php.ini.j2', dest: '{{ php_config_directory }}/cli/php.ini' }
    - { src: 'pdo_mysql.ini.j2', dest: '{{ php_config_directory }}/mods-available/pdo_mysql.ini' }
  notify: restart php-fpm
