---
# file: roles/node/tasks/main.yml

- name: install latest node repo
  shell:
    cmd: curl -sL https://rpm.nodesource.com/setup_13.x | bash -
    warn: false
  tags:
    - node

- name: install nodejs & npm
  yum:
    name: nodejs
    state: present
  tags:
    - node

- name: set permissions
  file:
    name: "{{ server_directory }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0755
  tags:
    - node

- name: install required npm packages
  npm:
    path: "{{ server_directory }}"
    state: present
  tags:
    - node

