---
# tasks file for nextcloud

- name: download package
  get_url:
    url:  "{{ nextcloud_download_url }}"
    dest: /tmp/nextcloud.tar.bz2
    checksum: "sha256:{{ nextcloud_checksum}}"

- name: install nextcloud
  unarchive:
    src: /tmp/nextcloud.tar.bz2
    dest: /var/www
    remote_src: true
    creates: /var/www/nextcloud/occ
    owner: "{{ nginx_user}}"
    group: "{{ nginx_group }}"

- name: make necessary directories directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  loop:
    - "{{ nextcloud_data_directory }}"
    - "{{ nextcloud_data_directory }}/upload_tmp"
    - /usr/local/tmp/sessions

- name: perform initial nextcloud setup
  become_user: "{{ nginx_user }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: yes
  shell: >
    php occ  maintenance:install 
    --database mysql
    --database-name {{ nextcloud_database_name }} 
    --database-user {{ nextcloud_database_user }} 
    --database-pass {{ nextcloud_database_pass }} 
    --admin-user {{ nextcloud_admin_user }} 
    --admin-pass '{{ nextcloud_admin_pass }}'
    --data-dir {{ nextcloud_data_directory }}
  args:
    chdir: /var/www/nextcloud/
    creates: /var/www/nextcloud/config/config.php

- name: set additional nextcloud config.php values
  become_user: "{{ nginx_user }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: yes
  shell: "php occ config:system:set trusted_domains 1 --value='{{ trusted_domain }}'"
  args:
    chdir: /var/www/nextcloud/

- name: Install news app
  become_user: "{{ nginx_user }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: yes
  shell: php occ app:install news
  args:
    chdir: /var/www/nextcloud/

- name: backup jobs, upgrade apps and database tuning
  become_user: "{{ nginx_user }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: yes
  shell: php occ {{ item }}
  args:
    chdir: /var/www/nextcloud/
  loop:
    - background:cron
    - upgrade
    - db:add-missing-indices
    - db:convert-filecache-bigint
    
- name: upgrade nextcloud
  become_user: "{{ nginx_user }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: yes
  shell: php occ upgrade
  args:
    chdir: /var/www/nextcloud/

- name: add nextcloud cronjob
  cron:
    name: nextcloud cronjob
    minute: '*/15'
    user: "{{ nginx_user }}"
    job: "php -f /var/www/nextcloud/cron.php > /dev/null 2>&1"
  
- name: run nextcloud cronjob
  become_user: "{{ nginx_user }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: yes
  shell: php -f /var/www/nextcloud/cron.php
  args:
    chdir: /var/www/nextcloud/
