---
# tasks file for nginx

- name: Create group for nginx
  group:
    name: "{{ nginx_group }}"
    system: true
    state: present

- name: Create the nginx user
  user:
    name: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    system: yes
    createhome: no
    state: present

- name: remove apache
  apt:
    name: apache2*
    state: absent
    purge: yes
    autoremove: yes

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0640
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: additional nginx configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ item }}"
  loop:
    - nextcloud.conf
    - header.conf
    - proxy.conf
    - optimization.conf
    - php_optimization.conf
    - ssl.conf
