---

- hosts: all
  tasks: 

  - name: import all roles
    include_role:
      name: "{{ item }}"
    loop:
      - requirements
      - php
      - mariadb
      - ssl
      - nginx
      - nextcloud
